---
title: "Impact of food availability and light on A. lixula larval growth - data analysis
  - model visualization"
output:
  html_document:
        keep_md: false
    fig_caption: true
  pdf_document: default
editor_options:
  markdown:
    
    wrap: 72
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r loading libraries, message=FALSE, warning=FALSE}
library('dplyr')
library('readr')
library('ggplot2')
library('knitr')
library('tidyr')
library('emmeans')
library('rstan')
rstan::rstan_options(auto_write = TRUE)
library('brms')
options(mc.cores = parallel::detectCores())  # run all cores
library('bayesplot')
library('marginaleffects')
library('ggdist')
```

```{r unscale_outcome}
unscale_outcome <- function(x){
  x = (x * sdL) + meanL
}
```

# 1. Data overview

Making a dataset containing only the data pertaining to *A. lixula* at 6
dpf.

```{r import data}
Al_df <-  read_delim("larval_morphology.csv", delim = ",",
                  col_types = "fffnfiffffiniif")
Al_df = drop_na(Al_df, length)
Al_df[Al_df$length < 0,]
# make Al_df$larva by concatenating Al_df$species with Al_df$larva 
Al_df$larva <- as.factor(paste0(Al_df$species, Al_df$larva))
Al_df <- Al_df[Al_df$species == "Al",]
Al_df <- Al_df[Al_df$dpf == "6",]
#ensure correct order for levels
Al_df<-Al_df %>% mutate(lit = factor(lit, levels = c("DD", "LD", "LL")))
Al_df<-Al_df %>% mutate(rod = factor(rod, levels = c("BR", "PO", "ALA")))

print(paste0('There are ', dim(Al_df)[1], ' measures from ', length(unique(Al_df$larva)), ' individual larvae.'))
```

```{r scaling variables}
meanL <- mean(Al_df$length)
sdL <- sd(Al_df$length)

Al_df$L  <- as.numeric(scale(Al_df$length))

Al_df <- droplevels(Al_df) # drop factor levels which are absent
head(Al_df)
```

# 3. Load best model

```{r}
dir.create("model_objects", showWarnings = FALSE)

url <- "https://github.com/MariaCoc/Urchin_phenotypic_plasticity/releases/download/v1.0.0/Al_rod_fed_lit_mod.rds"

local_file <- file.path("model_objects", "Al_rod_fed_lit_mod.rds")

if (!file.exists(local_file)) {
  download.file(url, local_file, mode = "wb") 
}

Al_rod_fed_lit_mod <- readRDS('model_objects/Al_rod_fed_lit_mod.rds')
Al_rod_fed_lit_mod
```

# 4. Marginaleffects plot with avg_predictions

```{r}
preds_df <- marginaleffects::avg_predictions(Al_rod_fed_lit_mod,
                  newdata = datagrid(fed = unique(Al_df$fed),
                            lit = unique(Al_df$lit),
                            rod = unique(Al_df$rod)
                            ),
                  by = c("lit","fed","rod"),
                  transform = unscale_outcome,
                  re_formula = NA
                  )

preds_df
```

We plot model predictions of the mean alongside the original data. The scaling and centering in the model has been reversed to show the predictions in the original scale. 

```{r fig.height=5, fig.width= 10}
ggplot() +
  # Add original data points
  geom_jitter(data = Al_df, aes(x = rod, y = length, color = fed), 
              position = position_jitterdodge(jitter.width = 0.25, dodge.width = 0.5), 
              size = 1, alpha = 0.4) +
  scale_colour_manual(values = c("#00BBC1", "#F86D63"), name = "Individual measures") +
  
  # Add the avg_predictions and error bars (95% CI)
  geom_point(data = preds_df, aes(x = rod, y = estimate, fill = fed),  # Use "response" column
             size = 2, position = position_dodge(width = 0.5)) +
  geom_errorbar(data = preds_df, aes(x = rod, ymin = conf.low, ymax = conf.high, fill = fed),
                width = 0.2, size = 0.7, position = position_dodge(width = 0.5)) + #, position = position_dodge(width = 0.5)) +
  scale_fill_manual(values = c("black", "black"), name = "avg_predictions") +
  
  # Facet by specific variables of interest
  facet_grid(~lit) +
  
  # Customize plot
  labs(title = "Average predictions for fed, conditioned on lit and rod",
       y = "Length in um", x = "Skeletal rod") +
  theme_bw() +
  theme(axis.text = element_text(size = 11), 
        axis.title = element_text(size = 13), 
        legend.title = element_text(size = 13),
        strip.text = element_text(size = 13),
        plot.title = element_text(size = 17, face = "bold"))

```

```{r fig.height=5, fig.width= 10}
ggplot() +
  # Add original data points with jittering
  geom_jitter(data = Al_df, aes(x = rod, y = length, color = lit), 
              position = position_jitterdodge(jitter.width = 0.25, dodge.width = 0.5), 
              size = 1, alpha = 0.6) +
  scale_colour_manual(values = c("#7473d1", "#f5b905","#d62222"), name= "Individual measures") +
  
  # Add the avg_predictions and error bars (95% CI)
  geom_point(data = preds_df, aes(x = rod, y = estimate, fill = lit), 
             size = 2, position = position_dodge(width = 0.5)) +
  geom_errorbar(data = preds_df, aes(x = rod, ymin = conf.low, ymax = conf.high, fill=lit), 
                width = 0.2, size = 0.7, position = position_dodge(width = 0.5)) +
  scale_fill_manual(values = c("black", "black", "black"), name="avg_predictions") +
  
  # Facet by specific variables of interest
  facet_grid(~ fed) +
  
  # Customize plot
  labs(title = "Average predictions for lit, conditioned on lit and rod",
       y = "Length um", x = "rod") +
  theme_bw() +
  theme(axis.text = element_text(size = 11), 
        axis.title = element_text(size = 13), 
        legend.title = element_text(size = 13),
        strip.text = element_text(size = 13),
        plot.title = element_text(size = 17, face = "bold"))
```
