---
title: "Impact of food availability, larval concentratiion and light on P. lividus larval growth - model visualization"
output:
  html_document:
    keep_md: false
    fig_caption: true
  pdf_document: default
editor_options:
  markdown:
    wrap: 72
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      dev = "tiff",
                      dpi = 300)
```

```{r loading libraies, message=FALSE, warning=FALSE}
library('dplyr')
library('readr')
library('ggplot2')
library('ggdist')
library('knitr')
library('tidyr')
library('emmeans')
library('rstan')
rstan::rstan_options(auto_write = TRUE)
library('brms')
options(mc.cores = parallel::detectCores())  # run all cores
library('bayesplot')
library('marginaleffects')
library('ggdist')
```

```{r unscale_outcome}
unscale_outcome <- function(x){
  x = (x * sdL) + meanL
}
```

# 1. Data overview

Making a dataset containing only the data on **P. lividus**

```{r import data}
Pl_df <-  read_delim("larval_morphology.csv", delim = ",",
                  col_types = "fffnfiffffiniif")
Pl_df = drop_na(Pl_df, length)
# make Pl_df$larva by concatenating Pl_df$species with Pl_df$larva 
Pl_df$larva <- as.factor(paste0(Pl_df$species, Pl_df$larva))
Pl_df <- Pl_df[Pl_df$species == "Pl",]
Pl_df <- Pl_df[Pl_df$length > 0,]
Pl_df <- Pl_df[! is.na(Pl_df$length),]
#ensure correct order for levels
Pl_df<-Pl_df %>% mutate(lit = factor(lit, levels = c("DD", "LD", "LL")))
Pl_df<-Pl_df %>% mutate(rod = factor(rod, levels = c("BR", "PO", "ALA")))

print(paste0('There are ', dim(Pl_df)[1], ' measures from ', length(unique(Pl_df$larva)), ' individual larvae.'))
```

```{r scaling variables}
meanL <- mean(Pl_df$length)
sdL <- sd(Pl_df$length)
meanC <- mean(Pl_df$lar_ml)
sdC <- sd(Pl_df$lar_ml)

Pl_df$L  <- as.numeric(scale(Pl_df$length))
Pl_df$C  <- as.numeric(scale(Pl_df$lar_ml))

Pl_df <- droplevels(Pl_df) # drop factor levels which are absent
head(Pl_df)
```

# 2. Load best model

```{r}
dir.create("model_objects", showWarnings = FALSE)

url <- "https://github.com/MariaCoc/Urchin_phenotypic_plasticity/releases/download/v1.0.0/Pl_rod_C_fed_lit_mod.rds"

local_file <- file.path("model_objects", "Pl_rod_C_fed_lit_mod.rds")

if (!file.exists(local_file)) {
  download.file(url, local_file, mode = "wb") 
}

Pl_rod_C_fed_lit_mod <- readRDS('model_objects/Pl_rod_C_fed_lit_mod.rds')
Pl_rod_C_fed_lit_mod
```

# 3. Marginaleffects plot with avg_predictions

```{r}
preds_df <- marginaleffects::avg_predictions(Pl_rod_C_fed_lit_mod,
                  newdata = datagrid(fed = unique(Pl_df$fed),
                            lit = unique(Pl_df$lit),
                            rod = unique(Pl_df$rod),
                            C = unique(Pl_df$C)
                            ),
                  by = c("C","lit", "rod","fed"),
                  transform = unscale_outcome,
                  re_formula = NA
                  )
preds_df$lar_ml     <- (preds_df$C * sdC) + meanC 
preds_df$lar_ml <- (preds_df$C * sdC) + meanC

head(preds_df, 10)
```

Check levels for lar_ml

```{r}
unique(preds_df$lar_ml)
```

We plot model predictions of the mean alongside the original data. The scaling and centering in the model has been reversed to show the predictions in the original scale. 


```{r fig.height=6, fig.width= 10}
ggplot() +
  # Add original data points
  geom_jitter(data = Pl_df, aes(x = C, y = length, color = fed), 
              position = position_jitterdodge(jitter.width = 0.25, dodge.width = 0.5), 
              size = 1, alpha = 0.4) +
  scale_colour_manual(values = c("#00BBC1", "#F86D63"), name = "Individual measures") +
  
  # Facet by specific variables of interest
  facet_grid(lit~rod) +
  
  # Add the avg_predictions and error bars (95% CI)
  geom_point(data = preds_df, aes(x = C, y = estimate, fill = fed),  # Use "response" column
             size = 2, position = position_dodge(width = 0.5)) +
  geom_errorbar(data = preds_df, aes(x = C, ymin = conf.low, ymax = conf.high, fill = fed),
                width = 0.2, size = 0.7, position = position_dodge(width = 0.5)) +
  scale_fill_manual(values = c("black", "black"), name = "avg_predictions") +
  
  # Customize plot
  labs(title = "Average predictions for fed, conditioned on lit and rod",
       y = "Length in um", x = "larvae/mL") +
  theme_bw() +
  theme(axis.text = element_text(size = 11), 
        axis.title = element_text(size = 13), 
        legend.title = element_text(size = 13),
        strip.text = element_text(size = 13),
        plot.title = element_text(size = 17, face = "bold"))

```



```{r fig.height=6, fig.width= 10}
ggplot() +
  # Add original data points
  geom_jitter(data = Pl_df, aes(x = lar_ml, y = length, color = fed), 
              position = position_jitterdodge(jitter.width = 2, dodge.width = 0), 
              size = 0.8, alpha = 0.5) +
  scale_colour_manual(values = c("#00BBC1", "#F86D63"), name = "Individual measures") +

  
  # Add the avg_predictions and error bars (95% CI)
  geom_smooth(data = preds_df, aes(x = lar_ml, y = estimate, color = fed), 
        size = 1, method = "lm")+
        scale_fill_manual(values = c("#00BBC1", "#F86D63"), name = "avg_predictions") +
  
  geom_ribbon(data = preds_df, aes(x = lar_ml, ymin = conf.low, ymax = conf.high, fill =fed), 
             alpha = 0.3) +
             scale_fill_manual(values = c("#00BBC1", "#F86D63"), name = "avg_predictions") +
  
  # Facet by specific variables of interest
  facet_grid(lit~rod) +  
  
  # Customize x-axis values
  scale_x_continuous(breaks = c(12.5, 25, 50), labels = c("12.5", "25", "50")) +
  
  # Customize plot
  labs(title = "Average predictions for fed, conditioned on lit, larval concentartion and rod",
       y = "Length in um", x = "larvae/mL") +
  theme_bw() +
  theme(axis.text = element_text(size = 11), 
        axis.title = element_text(size = 13), 
        legend.title = element_text(size = 13),
        strip.text = element_text(size = 13),
        plot.title = element_text(size = 17, face = "bold"))


```

```{r fig.height=6, fig.width= 10}
ggplot() +
  # Add original data points
  geom_jitter(data = Pl_df, aes(x = C, y = length, color = lit), 
              position = position_jitterdodge(jitter.width = 0.25, dodge.width = 0.5), 
              size = 1, alpha = 0.4) +
  scale_colour_manual(values = c( "#7473d1", "#f5b905"), name = "Individual measures") +
  
  # Facet by specific variables of interest
  facet_grid(fed~rod) +
  
  # Add the avg_predictions and error bars (95% CI)
  geom_point(data = preds_df, aes(x = C, y = estimate, fill = lit),  # Use "response" column
             size = 2, position = position_dodge(width = 0.5)) +
  geom_errorbar(data = preds_df, aes(x = C, ymin = conf.low, ymax = conf.high, fill = lit),
                width = 0.2, size = 0.7, position = position_dodge(width = 0.5)) +
  scale_fill_manual(values = c("black", "black"), name = "avg_predictions") +
  
  # Customize plot
  labs(title = "Average predictions for lit, conditioned on fed, larval concentartion and rod",
       y = "Length in um", x = "larvae/mL") +
  theme_bw() +
  theme(axis.text = element_text(size = 11), 
        axis.title = element_text(size = 13), 
        legend.title = element_text(size = 13),
        strip.text = element_text(size = 13),
        plot.title = element_text(size = 17, face = "bold"))

```

```{r fig.height=6, fig.width= 10}
ggplot() +
  # Add original data points
  geom_jitter(data = Pl_df, aes(x = rod, y = length, color = lit), 
              position = position_jitterdodge(jitter.width = 0.25, dodge.width = 0.5), 
              size = 1, alpha = 0.4) +
  scale_colour_manual(values = c("#7473d1", "#f5b905"), name = "Individual measures") +
  
  # Facet by specific variables of interest
  facet_grid(fed~C) +
  
  # Add the avg_predictions and error bars (95% CI)
  geom_point(data = preds_df, aes(x = rod, y = estimate, fill = lit),  # Use "response" column
             size = 2, position = position_dodge(width = 0.5)) +
  geom_errorbar(data = preds_df, aes(x = rod, ymin = conf.low, ymax = conf.high, fill = lit),
                width = 0.2, size = 0.7, position = position_dodge(width = 0.5)) +
  scale_fill_manual(values = c("black", "black"), name = "avg_predictions") +
  
  # Customize plot
  labs(title = "Average predictions for lit, conditioned on fed, larval concentartion and rod",
       y = "Length in um", x = "Skeletal rod") +
  theme_bw() +
  theme(axis.text = element_text(size = 11), 
        axis.title = element_text(size = 13), 
        legend.title = element_text(size = 13),
        strip.text = element_text(size = 13),
        plot.title = element_text(size = 17, face = "bold")) #, panel.grid =element_line(color="gray80")

```

```{r fig.height=6, fig.width= 10}
ggplot() +
  # Add original data points
  geom_jitter(data = Pl_df, aes(x = rod, y = length, color = lit), 
              position = position_jitterdodge(jitter.width = 0.25, dodge.width = 0.5), 
              size = 1, alpha = 0.4) +
  scale_colour_manual(values = c("#7473d1", "#f5b905"), name = "Individual measures") +
  
  # Facet by specific variables of interest
  facet_grid(fed~lar_ml) +
  
  # Add the avg_predictions and error bars (95% CI)
  geom_point(data = preds_df, aes(x = rod, y = estimate, fill = lit),  # Use "response" column
             size = 2, position = position_dodge(width = 0.5)) +
  geom_errorbar(data = preds_df, aes(x = rod, ymin = conf.low, ymax = conf.high, fill = lit),
                                width = 0.2, size = 0.7, position = position_dodge(width = 0.5)) +
  scale_fill_manual(values = c("black", "black"), name = "avg_predictions") +
  
  # Customize plot
  labs(title = "Average predictions for lit, conditioned on fed, larval concentartion and rod",
       y = "Length in um", x = "Skeletal rod") +
  theme_bw() +
  theme(axis.text = element_text(size = 11), 
        axis.title = element_text(size = 13), 
        legend.title = element_text(size = 13),
        strip.text = element_text(size = 13),
        plot.title = element_text(size = 17, face = "bold"))

```

# using C_vals

```{r}
C_vals = seq(from = min(Pl_df$C), to = max(Pl_df$C), length.out=100)

preds_df <- marginaleffects::avg_predictions(Pl_rod_C_fed_lit_mod,
                  newdata = datagrid(fed = unique(Pl_df$fed),
                            C = C_vals, #unique(Pl_df$C),  
                            lit = unique(Pl_df$lit),
                            rod = unique(Pl_df$rod)
                            ),
                  by = c("C","fed","rod","lit"),
                  transform = unscale_outcome,
                  re_formula = NA
                  )

preds_df$lar_ml <- (preds_df$C * sdC) + meanC 
preds_df$lar_ml <- (preds_df$C * sdC) + meanC
preds_df
```

```{r fig.height=6, fig.width= 10}
preds_df %>%
  ggplot(aes(x = lar_ml, y = estimate, color = fed)) +
  # Add original data points
  geom_point(data = Pl_df, aes(x = lar_ml, y = length, color = fed), 
         position = position_jitter(width = 2), size = 0.9, alpha = 0.6)+  
         scale_colour_manual(values = c("#00BBC1", "#F86D63"), name="Individual measures") +
 
  geom_smooth(data = preds_df, aes(x = lar_ml, y = estimate, color = fed), 
        size = 1, method = "lm")+
  scale_fill_manual(values = c("#00BBC1", "#F86D63"), name = "avg_predictions") +
  geom_ribbon(data = preds_df, 
             aes(x = lar_ml, ymin = conf.low, ymax = conf.high, fill =fed), 
                 alpha = 0.4) +
  scale_fill_manual(values = c("#00BBC1", "#F86D63"), name = "avg_predictions") +

  # Facet by specific variables of interest
  facet_grid(lit ~ rod) +
  
  # Customize x-axis values
  scale_x_continuous(breaks = c(12.5, 25, 50), labels = c("12.5", "25", "50")) +

  # Customize plot
  labs(title = "Average predictions for fed, conditioned on lit, larval concentartion and rod",
       y = "Length um", x = "Larvae/mL") +
  theme_bw() +
  theme(axis.text = element_text(size = 11), 
        axis.title = element_text(size = 13), 
        legend.title = element_text(size = 13),
        plot.title = element_text(size = 14, face = "bold"))

```

```{r fig.height=6, fig.width= 10}
preds_df %>%
  ggplot(aes(x = lar_ml, y = estimate, color = lit)) +
 # Add original data points
  geom_point(data = Pl_df, aes(x = lar_ml, y = length, color = lit), 
           position = position_jitter(width = 2), size = 0.9, alpha = 0.6)+  
           scale_colour_manual(values = c("#7473d1", "#FFB74D"), name = "Individual measures") +
 
  geom_smooth(data = preds_df, aes(x = lar_ml, y = estimate, color = lit), 
         size = 1, method = "lm")+
  scale_fill_manual(values = c("#7473d1", "#FFB74D"), name = "avg_predictions") +
  geom_ribbon(data = preds_df, 
             aes(x = lar_ml, ymin = conf.low, ymax = conf.high, fill = lit), 
             alpha = 0.4) +
  scale_fill_manual(values = c("#7473d1", "#FFB74D"), name = "avg_predictions") +

  # Facet by specific variables of interest
  facet_grid(fed ~ rod) +
  
  # Customize x-axis values
  scale_x_continuous(breaks = c(12.5, 25, 50), labels = c("12.5", "25", "50")) +

  # Customize plot
  labs(title = "Average predictions for lit, conditioned on fed, larval concentartion and rod",
       y = "Length um", x = "Larvae/mL") +
  theme_bw() +
  theme(axis.text = element_text(size = 11), 
      axis.title = element_text(size = 13), 
      legend.title = element_text(size = 13),
      plot.title = element_text(size = 14, face = "bold"))
```
